[package]
name = "embed-doc-image-showcase"
version = "0.2.0"
edition = "2021"
readme = "README.md"
license = "MIT"
description = "Showcase for the embed-doc-images crate"
documentation = "https://docs.rs/embed-doc-image-showcase"

[dependencies]
doc-image-embed = { version = "0.2", path = ".." }
